{% set name = "mtenn" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  git_url: https://github.com/choderalab/{{ name }}.git
  git_rev: {{ version }}
  git_depth: -1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - setuptools
    - pip
    - python >=3.6
    - versioningit
  run:
    - python >=3.6
    - pytorch
    - pytorch_geometric
    - pytorch_cluster
    - pytorch_scatter
    - pytorch_sparse
    - numpy
    - h5py
    - e3nn
    - dgllife
    - dgl
    - rdkit
    - ase
    - pytest
    - pydantic >=1.10.8,<2.0.0a0
    - fsspec

test:
  imports:
    - mtenn
  requires:
    - pip
    - pytest
  commands:
    - python -Ic "import mtenn; print(mtenn.__version__)"
    - pytest -v --pyargs mtenn

about:
  home: https://github.com/choderalab/mtenn
  summary: 'mtenn: Modular Training and Evaluation of Neural Networks'
  description: |
    Modular Training and Evaluation of Neural Networks for physics based models in chemistry.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/choderalab/mtenn
  dev_url: https://github.com/choderalab/mtenn

extra:
  recipe-maintainers:
    - hmacdope
    - mikemhenry
    - kaminow
