{% set name = "mtenn" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/choderalab/{{ name }}/archive/{{ version }}.tar.gz
  sha256: b78f6cf8ec9331c6e0772d55dfc7858cb61fd7da562a7bb47423811feddf2db4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - versioningit
  run:
    - python >=3.6
    - pytorch
    - pytorch_geometric
    - pytorch_cluster
    - pytorch_scatter
    - pytorch_sparse
    - numpy
    - h5py
    - e3nn
    - dgllife
    - dgl
    - rdkit
    - ase
    - pytest

test:
  imports:
    - mtenn
  requires:
    - pip
    - pytest
  commands:
    - python -Ic "import mtenn; print(mtenn.__version__)"
    - pytest -v --pyargs mtenn

about:
  home: https://github.com/choderalab/mtenn
  summary: 'mtenn: Modular Training and Evaluation of Neural Networks'
  description: |
    Modular Training and Evaluation of Neural Networks for physics based models in chemistry.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/choderalab/mtenn
  dev_url: https://github.com/choderalab/mtenn

extra:
  recipe-maintainers:
    - hmacdope
    - mikemhenry
    - kaminow
